# Generated by Django 3.1.6 on 2021-02-14 04:46

from django.db import migrations
import hiarc.models


class Migration(migrations.Migration):

    dependencies = [
        ('hiarc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', hiarc.models.UserManager()),
            ],
        ),
    ]
